/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetoa3;

/**
 *
 * @author Alunos
 */
public class Animais extends javax.swing.JFrame {

    /**
     * Creates new form Animais
     */
    public Animais() {
        initComponents();
        
        DB db = new DB("BancoDados.db");
        
        db.query("SELECT * from Animais");
        String cols[] = {"CODIGO", "NOME CIENTIFICO", "NOME POPULAR", "SEXO", "CLASSE", "POPULAÇÃO"};
        String fields[] = {"Código", "Nome científico", "Nome popular", "Sexo", "Classe", "População"};
        TableRender.render(table, cols, fields, db);
        while(db.next()){
            int codigo = db.getInt("Código");
            String animal = db.getString("Nome Popular");
            System.out.println("Código: " + codigo);
            System.out.println("Nome Popular: " + animal);
           }
        db.closeConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        novoanimal = new javax.swing.JToggleButton();
        removeranimal = new javax.swing.JToggleButton();
        atualizarTabela = new javax.swing.JButton();
        edicao = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        novoanimal.setText("Adicionar animal");
        novoanimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoanimalActionPerformed(evt);
            }
        });

        removeranimal.setText("Remover animal");
        removeranimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeranimalActionPerformed(evt);
            }
        });

        atualizarTabela.setText("Atualizar Tabela");
        atualizarTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarTabelaActionPerformed(evt);
            }
        });

        edicao.setText("Editar animal");
        edicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edicaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(novoanimal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edicao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(atualizarTabela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(removeranimal)
                .addGap(14, 14, 14))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novoanimal)
                    .addComponent(removeranimal)
                    .addComponent(atualizarTabela)
                    .addComponent(edicao))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void novoanimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoanimalActionPerformed
        botao cadastro = new botao();
        cadastro.setVisible(true);
    }//GEN-LAST:event_novoanimalActionPerformed

    private void removeranimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeranimalActionPerformed
        var linhaSelecionada = table.getSelectedRow();
        var codigo = table.getValueAt(linhaSelecionada, 0);
        
        DB db = new DB("BancoDados.db");
        var query = "DELETE FROM Animais WHERE Código = " + codigo; 
        db.execQuery(query);
    }//GEN-LAST:event_removeranimalActionPerformed

    private void atualizarTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarTabelaActionPerformed
        this.dispose();
        
        DB db = new DB("BancoDados.db");
        
        db.query("SELECT * from Animais");
        String cols[] = {"CODIGO", "NOME CIENTIFICO", "NOME POPULAR", "SEXO", "CLASSE", "POPULAÇÃO"};
        String fields[] = {"Código", "Nome científico", "Nome popular", "Sexo", "Classe", "População"};
        TableRender.render(table, cols, fields, db);
        while(db.next()){
            int codigo = db.getInt("Código");
            String animal = db.getString("Nome Popular");
            System.out.println("Código: " + codigo);
            System.out.println("Nome Popular: " + animal);
           }
        
        this.setVisible(true);
        
        db.closeConnection();
    }//GEN-LAST:event_atualizarTabelaActionPerformed

    private void edicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edicaoActionPerformed
        edicao edit = new edicao();
        edit.setVisible(true);
    }//GEN-LAST:event_edicaoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarTabela;
    private javax.swing.JButton edicao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton novoanimal;
    private javax.swing.JToggleButton removeranimal;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
